### PR TITLE
Switch to ember input helper

### PR DESCRIPTION
**Pull request by rwwagner90**
Just kidding, this doesn't fix the issue, but it is a step in the right direction.

### CODE REVIEW

**Comment by knownasilya** [comment]
We probably want to follow something like https://ember-twiddle.com/ac4ea1deedfcb7cb2b13a40c3f166932?openFiles=templates.application.hbs%2C

**Comment by rwwagner90** [comment]
@knownasilya this doesn't have a failing test case, just switched to the input helper, which seems to work fine. This is not part of the refactor we discussed yet.

**Comment by knownasilya** [comment]
Give https://github.com/knownasilya/ember-toggle/tree/simplify a try.

**Comment by knownasilya** [comment]
Also see https://github.com/knownasilya/ember-toggle/blob/simplify/tests/dummy/app/templates/application.hbs#L184

**Comment by rwwagner90** [comment]
@knownasilya tentatively looks okay. I like all the code deletion 😄 .

I think it should still use the ember input helper. Is there a reason we couldn't merge this PR?

Let me test out the new branch and if everything works, would you mind me doing a bit of cleanup, like using the input helper and submitting a PR or are you pretty set on things the way they are?

**Pull request closed without merging**
