### PR TITLE
Add material design toggle theme #90

### PR DESCRIPTION
**Pull request by mcoirault**
Here is my PR related to issue #90.
I'm fairly new to contributions like these so hopefully I made it properly.

### CODE REVIEW

**Comment by lolmaus** [comment]
I've deployed the demo of this branch for convenience: https://lolmaus.github.io/ember-toggle/

**Comment by lolmaus** [comment]
@mcoirault Are the styles hand-written or copied over from some Material Design kit?

**Comment by lolmaus** [comment]
BTW, why a pink hue? I've tried a few Material kits online and they all have teal toggles.

Maybe it makes sense to make the toggle configurable. On the other hand, it can be configured with CSS... :thinking:

**Comment by knownasilya** [comment]
FYI the drag doesn't work on that toggle.

**Comment by knownasilya** [comment]
We should probably do green, since all of the active states are green by default, except for the default switch.. weird.

**Comment by mcoirault** [comment]
I went with the green used by the flat theme. I also modified the css to follow more closely the [material guidelines](https://material.io/guidelines/components/selection-controls.html#selection-controls-switch).

As for the drag not working, it seems like it was due to the first one not having value and onToggle attributes. So I've added those two attributes back into the dummy page and it's working fine now. This might be an issue to look into.

**Pull request merged**
