### PR TITLE
fix: app componentes to classic style

### PR DESCRIPTION
**Pull request by webark**
was running into problems with using `podMoudlePrefix` and this addon.

### CODE REVIEW

**Comment by knownasilya** [comment]
@webark want to be added as a contributor?

**Comment by webark** [comment]
@knownasilya sure! what are some of your short and long term goals?

**Comment by rwwagner90** [comment]
@webark can you elaborate on the issues you encountered here? Is `podModulePrefix` still something that should be used?

**Comment by webark** [comment]
@rwwagner90 we where using a `podModulePrefix` of 'ui' so we where having to add in dummy "import only" components in order to get it working. Exporting the app side in classic structure sidesteps the issues..

**Comment by webark** [comment]
@rwwagner90 here's an example.. https://github.com/webark/toggle-example

**Comment by knownasilya** [comment]
@webark well long term I want to make this into glimmer components. I started experimenting with component-managers in https://github.com/knownasilya/ember-toggle/tree/experimental/glimmer but some things are still lacking in Ember. I'd also like to polish up the styles and add internal labels for all of the switches. Maybe add some other styles too.

**Comment by knownasilya** [comment]
@webark @rwwagner90 I added you both to npm as well, so you can do releases.

**Pull request merged**
