### PR TITLE
fix: Updated ember-gesture-modifiers to ^5.0.0

### LINKED ISSUE #185: Update ember-gesture-modifiers dependency
ember-gesture-modifiers 5.0.0 has expanded the version range for ember-modifier. Could you please update this so that we can update our ember-modifier?

### PR DESCRIPTION
**Pull request by cah-yu-yuan**
Fixes https://github.com/knownasilya/ember-toggle/issues/185

### CODE REVIEW

**Comment by knownasilya** [comment]
Thanks @cah-yu-yuan. Letting the tests run, once they are green I'll merge and release. If I forget, please ping me.

**Comment by cah-brian-gantzler** [comment]
Not really sure what the problem even is with the tests, but I think it might be with ember-try. See https://github.com/ember-cli/ember-try/pull/912.  There is a release 3.0.0-beta.1

**Comment by cah-brian-gantzler** [comment]
Anyway to kick off the tests on main? Wonder when the last time they worked was. Sorry to cause you more work for such a simple change

**Comment by knownasilya** [comment]
Going to fix it here, I'm sure the issue probably exists on main. Most of my work has been mostly in https://github.com/knownasilya/ember-toggle/pull/174 but that's still a bit away from being finished.

**Comment by cah-brian-gantzler** [comment]
In no rush for the PR. Still waiting on a couple other addons to expand the ember-modifer version. Was just trying to help. Will wait. Thanks for all your efforts

**Comment by knownasilya** [comment]
Do you need ember 3.24 support or is 3.28 fine?

**Comment by cah-brian-gantzler** [comment]
We are on 4.11

**Comment by knownasilya** [comment]
@cah-yu-yuan could you rebase? I can merge and release this after that.

**Comment by cah-yu-yuan** [comment]
This has been rebased, please approve the workflow

**Comment by knownasilya** [comment]
Looks like an error `Cannot find module 'babel-plugin-dynamic-import-node/utils'`

**Comment by knownasilya** [comment]
I'll update the CI. Thanks for looking into it!

**Review by knownasilya — APPROVED** [review]

**Comment by knownasilya** [comment]
Hum, I updated master but still seeing the error. Will try to give it more of a look tomorrow.

**Pull request merged**
