### PR TITLE
Fix #91 `x-toggle` toggles on click when the `onToggle` action does not update the value

### LINKED ISSUE #91: `x-toggle` toggles on click when the `onToggle` action does not update the value
## How to reproduce

```js
{
  value: false,
  
  actions: {
    toggle () {}
  }
}
```

```handlebars
<p>value: {{value}}</p>

{{x-toggle value=value onToggle=(action 'toggle')}}
```

image

Now click the toggle.

## What I expect to happen

The component should not toggle because the action does not update the value.

## What actually happens

image

The component does toggle, the value and the component's state are out of sync.

## Reproduction

https://ember-twiddle.com/85bcda587638b642fcf254d550488899?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

## Notes

Happens only for clicking. Dragging works correctly: the component toggles only when the action updates the value.

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Comment by knownasilya** [comment]
@lolmaus any chance you tested this on anything but chrome?

**Comment by lolmaus** [comment]
Will test manually in our app via BrowserStack.

**Comment by FredUK** [comment]
I have tested it manually on my app with Chrome, IE11, Edge and Chrome for Android. It all worked fine.

**Comment by lolmaus** [comment]
@FredUK Thank you for QAing this. :heart: 

I hope to finalize it early next week.

This PR revealed that drag-to-toggle #49 is incompatible with `window.confirm()`, and there is no solution. The workaround is to use a custom async dialog instead of the sync `confirm()`, which is fine because `confirm()` is considered to be a somewhat bad practice anyway.

I'm gonna add to readme a warning not to use `confirm()` in the `onToggle` action. Gonna do it as part of this PR because confirmation/rejection is the primary use case of not changing the value from the action handler.

This is not supported since 5.1:

```js
actions: {
  toggle (newValue) {
    if (!newValue) {
      return;
    }

    if (confirm('Are you sure?')) {
      this.set('value', newValue);
    }
  }
}
```

Suggested replacement:

```js
actions: {
  toggle (newValue) {
    if (!newValue) {
      return;
    }

    this.get('customService').confirm('Are you sure?', () => {
      this.set('value', newValue);
    });
  }
}
```

Also gonna implement such a custom confirm as an Ember addon. There's already https://github.com/AnnotationSro/ember-confirm-dialog , but it is template-driven, while I want the API to be as close to `window.confirm()` as possible, like in the example above.

**Comment by knownasilya** [comment]
I usually do something like:

```hbs
{{x-toggle onToggle=(action (mut showConfirmation) true)}}

{{#if showConfirmation}}
  {{confirmation-modal onConfirm=(action (mut value))}}
{{/if}}
```

**Comment by lolmaus** [comment]
@knownasilya Yep. My goal is to avoid dozens of identical confirmation modal entries across templates. Luckily, this is out of scope of ember-toggle.

**Comment by FredUK** [comment]
No problem @lolmaus , I'm also doing something similar to @knownasilya . My toggle mutates a property which will display a modal with ember-elsewhere (which I use to replace the old liquid-fire modal).

As you said, I also believe confirmation modal is outside the scope of ember-toggle and should be implemented by the developer. You might want to use different modals depending on the toggle itself.

```
{{x-toggle value=(readonly statusEnabled) onToggle=(action (mut showModal))

{#if showModal}}
   {{to-elsewhere
      named='modal'
      send=(hash
        body=(
          component "confirm-modal"
          close=(action (mut showModal) false)
          confirmTitle=(t (concat-strings 'index.' (if statusEnabled 'toggle_off_title' 'toggle_on_title')))
          confirmMessage=(t (concat-strings 'index.' (if statusEnabled 'toggle_off_message' 'toggle_on_message')))
          confirm=(action (mut statusEnabled))
        onOutsideClick=(action (mut showModal) false))
      }}
{{/if}}
```

**Comment by lolmaus** [comment]
I have created [ember-dialogs](https://github.com/lolmaus/ember-dialogs) over the weekend. Today I've tried it out in our app together with this PR. It works smoothly!

The approach suggested by @knownasilya and @FredUK will also work.

@knownasilya This should be ready to merge. Please review. :bow:

**Comment by knownasilya** [comment]
@lolmaus do you think we can warn in the console if the user forgot to update the value?

**Comment by lolmaus** [comment]
@knownasilya No, because it may be deliberate. Here's what were'doing for example:

```js
        toggleAuthz(newValue) {
            const message = newValue
                ? ENABLE_AUTHZ_CONFIRMATION_MESSAGE
                : DISABLE_AUTHZ_CONFIRMATION_MESSAGE;

            this.get("dialogs").confirm({
                message,
                actionOk: () => {
                    const repository = this.get("repository");

                    repository.set("authorizationEnabled", newValue);

                    repository
                        .save()
                        .then(() => {
                            newValue
                                ? repository
                                    .hasMany(this.get("relationshipName"))
                                    .reload()

                                : this._unloadAllRepositoryMembers(repository);

                            this.get("scope").updateRepositoryRoles();
                        })
                        .catch(() => repository.rollbackAttributes());
                }
            });
        }
```

We wouldn't want to see warnings for a valid use case. If we introduce warnings, we also need to provide a way of opting out of them. We'd need to design API for `this.set('iKnowWhatImDoing', true)`.

**Comment by lolmaus** [comment]
Tried releasing. `npm run release` went smoothly, but the subsequent command partially failed:

```
$ git push --follow-tags origin master; npm publish
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 762 bytes | 0 bytes/s, done.
Total 6 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least one approved review is required by reviewers with write access.
To git@github.com:knownasilya/ember-toggle.git
 * [new tag]         v5.1.2 -> v5.1.2
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:knownasilya/ember-toggle.git'
+ ember-toggle@5.1.2
```

Something about `master` being protected. Do I need to submit a PR for 2d210b9 "chore(release): 5.1.2" to make it into `master`?

**Comment by knownasilya** [comment]
Unfortunately, you will have to submit a pr, it's a limitation of what can be done with protected branches.

**Pull request merged**
