### PR TITLE
Simplify to master

### PR DESCRIPTION
**Pull request by rwwagner90**
@knownasilya I think the simplify branch is pretty much good to go, at least to be merged to master, but maybe not quite 5.0 yet. Figured I would open a PR to get master up to date.

### CODE REVIEW

**Comment by gtb104** [comment]
The last PR didn't remove `ember-browser-checker`. I believe that service is no longer being used, so should be removed.

**Comment by webark** [comment]
ya.. that's correct. Thanks for all the great work on this!! 😊

**Comment by webark** [comment]
🎉

**Comment by knownasilya** [comment]
alpha.5 published

**Pull request merged**
