### PR TITLE
Removed width attribute from x-toggle-container (now width:auto;)

### PR DESCRIPTION
**Pull request by Techn1x**
Fixes https://github.com/knownasilya/ember-toggle/issues/82

### CODE REVIEW

**Comment by knownasilya** [comment]
@lolmaus @rwjblue @webark any thoughts on this change. I know it's small, but it might have big consequences, i.e. breaking people's UIs. Personally, I haven't been able to replicate the issue, but that doesn't mean it doesn't exist.

**Comment by Techn1x** [comment]
Do you see the issue in the Twiddle that I made previously?
https://ember-twiddle.com/306112700222db6884344a56a24cccd3?openFiles=templates.application.hbs%2C

It looks like this for me (twiddle is using ember-toggle 5.0.2, before any size changes & before this PR's fix)
capture5

I can also see the issue occurring (very slightly) on the demo page. The labels to the right of switches are ever so slightly closer to the switch than the left label

Hopefully we can get to the bottom of this :)

**Comment by webark** [comment]
@knownasilya i'll take a look at it today.

**Comment by knownasilya** [comment]
Ping @webark

**Pull request closed without merging**
