### PR TITLE
Don't toggle when panning while disabled

### PR DESCRIPTION
**Pull request by lolmaus**
Totally overlooked this one. Sorry. :flushed:

### CODE REVIEW

**Comment by knownasilya** [comment]
👏

**Comment by knownasilya** [comment]
Published as 5.1.1

**Comment by knownasilya** [comment]
@lolmaus do you want to be added as a contributor?

**Comment by lolmaus** [comment]
@knownasilya Gladly. :bow:

**Comment by knownasilya** [comment]
Invite sent for github, and added to npm.

**Pull request merged**
